name: Deploy Qulang App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Rebuild and deploy Docker container
        run: |
          echo "tototo" | sudo -S bash -c "cd /root/chatbot.git && git pull && docker-compose down && docker-compose up -d --build"
          echo "script deployed on http://46.17.103.110:3001"
